config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'sheets/my_brackets' => 'sheets#my_brackets', :as => :my_brackets
  get 'sheets/get_points' => 'sheets#get_points', :as => :points
  get 'sheets/leaders' => 'sheets#leaders', :as => :leaders
  get 'sheets/lock_sheets' => 'sheets#lock_sheets', :as => :lock_sheets

  resources :sheets, except: [ :index ] do
    member do
      get :mark_paid
    end
  end
  
  resources :teams do
    member do
      get :team_lost
    end
  end

  root to: "home#index"
end

app/models/sheet.rb
class Sheet < ApplicationRecord
  belongs_to :user
  
  validates_presence_of :name, :round1g1a, :round1g2a, :round1g3a, :round1g4a, :round1g5a, :round1g6a, :round1g7a, 
    :round1g8a, :round1g9a, :round1g10a, :round1g11a, :round1g12a, :round1g13a, :round1g14a, :round1g15a, :round1g16a, 
    :round1g1b, :round1g2b, :round1g3b, :round1g4b, :round1g5b, :round1g6b, :round1g7b, :round1g8b, :round1g9b, 
    :round1g10b, :round1g11b, :round1g12b, :round1g13b, :round1g14b, :round1g15b, :round1g16b, :round2g1a, :round2g2a, 
    :round2g3a, :round2g4a, :round2g5a, :round2g6a, :round2g7a, :round2g8a, :round2g1b, :round2g2b, :round2g3b, 
    :round2g4b, :round2g5b, :round2g6b, :round2g7b, :round2g8b, :round3g1a, :round3g2a, :round3g3a, :round3g4a,
    :round3g1b, :round3g2b, :round3g3b, :round3g4b, :round4g1, :round4g2, :round4g3, :round4g4, :round5g1, :round5g2,
    :round6, :unless => :is_master? 
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  include Points
  
  before_filter :authenticate_user!
  before_action :set_sheet, only: [:show, :edit, :update, :destroy, :mark_paid]
  
  # def index
#     @sheets = Sheet.all
#
#     respond_to do |format|
#       format.html # index.html.erb
#       format.json { render json: @teams }
#     end
#   end
  
  def my_brackets
    authorize(Sheet)
    master_sheet = Sheet.where(is_master: true)
    @sheets = Sheet.where(user_id: current_user.id, is_master: false).order("name")
    @sheets = master_sheet + @sheets
    @master = Sheet.where(is_master: true).first
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sheets }
    end
  end
  
  def get_points
    authorize(Sheet)
    @master = Sheet.where("is_master = ?", true).first
    @sheets = Sheet.where("is_master = ?", false)
    @sheets.each do |sheet|
    	calculate(sheet, @master)
    end
    flash[:success] = "Points have been calculated"
    respond_to do |format|
      format.html { redirect_to leaders_path }
    end
  end
  
  def leaders
    authorize(Sheet)
    @sheets = Sheet.where("is_master = ?", false).order("total_points desc")
  end
  
  def lock_sheets
    authorize(Sheet)
    @sheets = Sheet.where("is_master = ?", false)
    @sheets.each do |sheet|
    	sheet.update_attribute(:is_locked, true)
    end
    flash[:success] = "Brackets are now locked"

    respond_to do |format|
      format.html { redirect_to root_path }
    end
  end
  
  def mark_paid
    authorize(@sheet)
    @sheet.update_attribute(:is_paid, true)
    redirect_to leaders_path
  end
  
  def new
    authorize(Sheet)
    @sheet = Sheet.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    authorize(@sheet)
  end

  def create
    authorize(Sheet)
    @sheet = Sheet.new(sheet_params)
    @sheet.user_id = current_user.id
    @sheet.last_edit_by = current_user.id
    respond_to do |format|
      if @sheet.save
        format.html { redirect_to(@sheet, :notice => 'Your bracket was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    authorize(@sheet)
    @sheet.last_edit_by = current_user.id
    respond_to do |format|
      if @sheet.update(sheet_params)
        format.html { redirect_to(@sheet, :notice => 'Your bracket was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def show
    authorize(@sheet)
    @master = Sheet.where("is_master = ?", true).first
    respond_to do |format|
      format.html # show.html.erb
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sheet
      @sheet = Sheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sheet_params
      params.require(:sheet).permit(:name, :round1g1a, :round1g2a, :round1g3a, :round1g4a, :round1g5a, :round1g6a, :round1g7a, 
    :round1g8a, :round1g9a, :round1g10a, :round1g11a, :round1g12a, :round1g13a, :round1g14a, :round1g15a, :round1g16a, 
    :round1g1b, :round1g2b, :round1g3b, :round1g4b, :round1g5b, :round1g6b, :round1g7b, :round1g8b, :round1g9b, 
    :round1g10b, :round1g11b, :round1g12b, :round1g13b, :round1g14b, :round1g15b, :round1g16b, :round2g1a, :round2g2a, 
    :round2g3a, :round2g4a, :round2g5a, :round2g6a, :round2g7a, :round2g8a, :round2g1b, :round2g2b, :round2g3b, 
    :round2g4b, :round2g5b, :round2g6b, :round2g7b, :round2g8b, :round3g1a, :round3g2a, :round3g3a, :round3g4a,
    :round3g1b, :round3g2b, :round3g3b, :round3g4b, :round4g1, :round4g2, :round4g3, :round4g4, :round5g1, :round5g2,
    :round6, :is_master, :round1pts, :round2pts, :round3pts, :round4pts, :round5pts, :round6pts, :total_points, :is_paid, :last_edit_by, :is_locked )
    end
end

app/views/sheets/_sheet.html.haml
%div
  %h3
    = sheet.name
    for #{current_user.fullname}
%table.mm{:summary => "Tournament Bracket"}
  %tr
    %td.mm
      %p.mm= sheet.round1g1a
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g1a
    %td.mm{:rowspan => "4"}
      %p.mm= sheet.round3g1a
    %td.mm{:rowspan => "8"}
      %p.mm= sheet.round4g1
    %td.mm{:rowspan => "16"}
      %p.mm= sheet.round5g1
    %td.mm{:rowspan => "8"}
      %p.mm= sheet.round6
    %td.mm{:rowspan => "16"}
      %p.mm= sheet.round5g2
    %td.mm{:rowspan => "8"}
      %p.mm= sheet.round4g3
    %td.mm{:rowspan => "4"}
      %p.mm= sheet.round3g1b
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g1b
    %td.mm
      %p.mm= sheet.round1g1b
  %tr
    %td.mm
      %p.mm= sheet.round1g2a
    %td.mm
      %p.mm= sheet.round1g2b
  %tr
    %td.mm
      %p.mm= sheet.round1g3a
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g2a
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g2b
    %td.mm
      %p.mm= sheet.round1g3b
  %tr
    %td.mm
      %p.mm= sheet.round1g4a
    %td.mm
      %p.mm= sheet.round1g4b
  %tr
    %td.mm
      %p.mm= sheet.round1g5a
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g3a
    %td.mm{:rowspan => "4"}
      %p.mm= sheet.round3g2a
    %td.mm{:rowspan => "4"}
      %p.mm= sheet.round3g2b
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g3b
    %td.mm
      %p.mm= sheet.round1g5b
  %tr
    %td.mm
      %p.mm= sheet.round1g6a
    %td.mm
      %p.mm= sheet.round1g6b
  %tr
    %td.mm
      %p.mm= sheet.round1g7a
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g4a
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g4b
    %td.mm
      %p.mm= sheet.round1g7b
  %tr
    %td.mm
      %p.mm= sheet.round1g8a
    %td.mm
      %p.mm= sheet.round1g8b
  %tr
    %td.mm
      %p.mm= sheet.round1g9a
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g5a
    %td.mm{:rowspan => "4"}
      %p.mm= sheet.round3g3a
    %td.mm{:rowspan => "8"}
      %p.mm= sheet.round4g2
    %td{:align => "center", :rowspan => "32"}
      = link_to "Edit Bracket", edit_sheet_path(sheet), :class => "btn btn-success"
      %p.mm
    %td.mm{:rowspan => "8"}
      %p.mm= sheet.round4g4
    %td.mm{:rowspan => "4"}
      %p.mm= sheet.round3g3b
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g5b
    %td.mm
      %p.mm= sheet.round1g9b
  %tr
    %td.mm
      %p.mm= sheet.round1g10a
    %td.mm
      %p.mm= sheet.round1g10b
  %tr
    %td.mm
      %p.mm= sheet.round1g11a
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g6a
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g6b
    %td.mm
      %p.mm= sheet.round1g11b
  %tr
    %td.mm
      %p.mm= sheet.round1g12a
    %td.mm
      %p.mm= sheet.round1g12b
  %tr
    %td.mm
      %p.mm= sheet.round1g13a
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g7a
    %td.mm{:rowspan => "4"}
      %p.mm= sheet.round3g4a
    %td.mm{:rowspan => "4"}
      %p.mm= sheet.round3g4b
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g7b
    %td.mm
      %p.mm= sheet.round1g13b
  %tr
    %td.mm
      %p.mm= sheet.round1g14a
    %td.mm
      %p.mm= sheet.round1g14b
  %tr
    %td.mm
      %p.mm= sheet.round1g15a
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g8a
    %td.mm{:rowspan => "2"}
      %p.mm= sheet.round2g8b
    %td.mm
      %p.mm= sheet.round1g15b
  %tr
    %td.mm
      %p.mm= sheet.round1g16a
    %td.mm
      %p.mm= sheet.round1g16b

app/views/sheets/edit.html.haml
= form_for @sheet do |f|
  = render "shared/error_messages", :target => @sheet
  %div
    = f.text_field :name, :placeholder => 'Bracket Name...'
    for #{@sheet.user.full_name}
  %table.mm{:summary => "Tournament Bracket"}
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g1a, Team.where("game = '1A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g1a, Team.where("game = '1A' or game = '2A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "4"}
        %p.mm= f.collection_select :round3g1a, Team.where("game = '1A' or game = '2A' or game = '3A' or game = '4A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "8"}
        %p.mm= f.collection_select :round4g1, Team.where("game = '1A' or game = '2A' or game = '3A' or game = '4A' or game = '5A' or game = '6A' or game = '7A' or game = '8A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "16"}
        %p.mm= f.collection_select :round5g1, Team.where("game = '1A' or game = '2A' or game = '3A' or game = '4A' or game = '5A' or game = '6A' or game = '7A' or game = '8A' or game = '9A' or game = '10A' or game = '11A' or game = '12A' or game = '13A' or game = '14A' or game = '15A' or game = '16A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "8"}
        %p.mm= f.collection_select :round6, Team.order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "16"}
        %p.mm= f.collection_select :round5g2, Team.where("game = '1B' or game = '2B' or game = '3B' or game = '4B' or game = '5B' or game = '6B' or game = '7B' or game = '8B' or game = '9B' or game = '10B' or game = '11B' or game = '12B' or game = '13B' or game = '14B' or game = '15B' or game = '16B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "8"}
        %p.mm= f.collection_select :round4g3, Team.where("game = '1B' or game = '2B' or game = '3B' or game = '4B' or game = '5B' or game = '6B' or game = '7B' or game = '8B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "4"}
        %p.mm= f.collection_select :round3g1b, Team.where("game = '1B' or game = '2B' or game = '3B' or game = '4B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g1b, Team.where("game = '1B' or game = '2B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g1b, Team.where("game = '1B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g2a, Team.where("game = '2A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g2b, Team.where("game = '2B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g3a, Team.where("game = '3A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g2a, Team.where("game = '3A' or game = '4A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g2b, Team.where("game = '3B' or game = '4B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g3b, Team.where("game = '3B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g4a, Team.where("game = '4A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g4b, Team.where("game = '4B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g5a, Team.where("game = '5A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g3a, Team.where("game = '5A' or game = '6A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "4"}
        %p.mm= f.collection_select :round3g2a, Team.where("game = '5A' or game = '6A' or game = '7A' or game = '8A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "4"}
        %p.mm= f.collection_select :round3g2b, Team.where("game = '5B' or game = '6B' or game = '7B' or game = '8B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g3b, Team.where("game = '5B' or game = '6B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g5b, Team.where("game = '5B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g6a, Team.where("game = '6A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g6b, Team.where("game = '6B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g7a, Team.where("game = '7A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g4a, Team.where("game = '7A' or game = '8A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g4b, Team.where("game = '7B' or game = '8B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g7b, Team.where("game = '7B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g8a, Team.where("game = '8A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g8b, Team.where("game = '8B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g9a, Team.where("game = '9A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g5a, Team.where("game = '9A' or game = '10A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "4"}
        %p.mm= f.collection_select :round3g3a, Team.where("game = '9A' or game = '10A' or game = '11A' or game = '12A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "8"}
        %p.mm= f.collection_select :round4g2, Team.where("game = '9A' or game = '10A' or game = '11A' or game = '12A' or game = '13A' or game = '14A' or game = '15A' or game = '16A'").order(:name), :name, :display_name, :include_blank => ''
      %td{:align => "center", :rowspan => "32"}
        %p.mm= f.submit "Update Bracket", :class => "btn-success"
      %td.mm{:rowspan => "8"}
        %p.mm= f.collection_select :round4g4, Team.where("game = '9B' or game = '10B' or game = '11B' or game = '12B' or game = '13B' or game = '14B' or game = '15B' or game = '16B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "4"}
        %p.mm= f.collection_select :round3g3b, Team.where("game = '9B' or game = '10B' or game = '11B' or game = '12B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g5b, Team.where("game = '9B' or game = '10B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g9b, Team.where("game = '9B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g10a, Team.where("game = '10A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g10b, Team.where("game = '10B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g11a, Team.where("game = '11A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g6a, Team.where("game = '11A' or game = '12A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g6b, Team.where("game = '11B' or game = '12B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g11b, Team.where("game = '11B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g12a, Team.where("game = '12A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g12b, Team.where("game = '12B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g13a, Team.where("game = '13A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g7a, Team.where("game = '13A' or game = '14A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "4"}
        %p.mm= f.collection_select :round3g4a, Team.where("game = '13A' or game = '14A' or game = '15A' or game = '16A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "4"}
        %p.mm= f.collection_select :round3g4b, Team.where("game = '13B' or game = '14B' or game = '15B' or game = '16B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g7b, Team.where("game = '13B' or game = '14B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g13b, Team.where("game = '13B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g14a, Team.where("game = '14A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g14b, Team.where("game = '14B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g15a, Team.where("game = '15A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g8a, Team.where("game = '15A' or game = '16A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm{:rowspan => "2"}
        %p.mm= f.collection_select :round2g8b, Team.where("game = '15B' or game = '16B'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g15b, Team.where("game = '15B'").order(:name), :name, :display_name, :include_blank => ''
    %tr
      %td.mm
        %p.mm= f.collection_select :round1g16a, Team.where("game = '16A'").order(:name), :name, :display_name, :include_blank => ''
      %td.mm
        %p.mm= f.collection_select :round1g16b, Team.where("game = '16B'").order(:name), :name, :display_name, :include_blank => ''

app/views/sheets/get_points.html.haml
.container
  %br/
  %br/
  %br/
  = link_to sheet.name, sheet
  = link_to 'Edit', edit_sheet_path(sheet)
  = sheet.round1g1a
  = sheet.total_points
  = succeed "Master:" do
    %br/
  = @master.round1g1a
  Sheets #{@sheets.count}

app/views/sheets/index.html.haml
%h1 Sheets#index
%p Find me in app/views/sheets/index.html.haml

app/views/sheets/leaders.html.haml
%div
  There are #{@sheets.size} entries. Contact gpasley@gmail.com if you have any questions about your score
  %table.leaders
    - if current_user.is_admin?
      %th Paid
    %th Name
    %th Bracket
    %th Final Four Teams
    %th Champion Pick
    %th Rd 1
    %th Rd 2
    %th Sweet 16
    %th Elite 8
    %th Final 4
    %th Final
    %th Total
    - @sheets.each_with_index do |sheet, i|
      - row_class = i%2 == 0 ? "even" : "odd"
      %tr{:class => row_class}
        - if current_user.is_admin?
          %td 
            %div{class: (sheet.is_paid? || "false")}
              = humanize_boolean(sheet.is_paid)
        %td= sheet.user.full_name
        %td= link_to sheet.name, sheet
        %td
          %span{class: team_loss(sheet.round4g1) && 'loss' }
            #{sheet.round4g1},
          %span{class: team_loss(sheet.round4g2) && 'loss' }
            #{sheet.round4g2},
          %span{class: team_loss(sheet.round4g3) && 'loss' }
            #{sheet.round4g3},
          %span{class: team_loss(sheet.round4g4) && 'loss' }
            #{sheet.round4g4}
        %td
          %span{class: team_loss(sheet.round6) && 'loss' }
            = sheet.round6
        %td= sheet.round1pts
        %td= sheet.round2pts
        %td= sheet.round3pts
        %td= sheet.round4pts
        %td= sheet.round5pts
        %td= sheet.round6pts
        %td= sheet.total_points