config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'sheets/my_brackets' => 'sheets#my_brackets', :as => :my_brackets
  get 'sheets/get_points' => 'sheets#get_points', :as => :points
  get 'sheets/leaders' => 'sheets#leaders', :as => :leaders
  get 'sheets/lock_sheets' => 'sheets#lock_sheets', :as => :lock_sheets

  resources :sheets, except: [ :index ] do
    member do
      get :mark_paid
    end
  end
  
  resources :teams do
    member do
      get :team_lost
    end
  end

  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    if user_signed_in?
      @picks = Sheet.where(is_master: false).group(:round6).order(:round6).size
      @sheet = Sheet.where("is_master = ?", true).first
      @leaders = Sheet.where("is_master = ?", false).order("total_points desc").limit(10)
      @locked = Sheet.where("is_locked = ?", true).first
    else
      redirect_to new_user_session_path
    end
  end
  
end

app/views/home/_logged_in.html.haml
.container.padtop
  .jumbotron
    .mytitle
      March Madness Brackets #{Time.now.strftime("%Y")}
  %br/
  %p
    %font{:color => "red"} Please review your bracket and contact gpasley@gmail.com for any corrections.  Otherwise, the higher seed will always be picked for the correction.
  - if user_signed_in?
    - if @locked.nil?
      = link_to 'Add Bracket', new_sheet_path, class: "btn-primary btn"
    - unless @sheet.nil?
      = link_to 'View Master Sheet', sheet_path(@sheet), class: "btn btn-info"
    - if current_user.is_admin?
      = link_to 'Calculate', points_path, class: "btn btn-success"
      - if @locked.nil?
        = link_to 'Lock', lock_sheets_path, class: "btn btn-danger"

      %br/

  .row
    .col-md-3
      %h2 Scoring
      %p Round 1 - 1pt
      %p Round 2 - 2pts
      %p Round 3 - 4pts
      %p Round 4 - 8pts
      %p Round 5 - 16pts
      %p Round 6 - 32pts
      %p *Points per win
      %br/
      %p 1st - $240
      %p 2nd - $120
      %p 3rd - $40
      %p Last - $10
    .col-md-4
      %h2 Champion Pick
      %table.table
        - @picks.each do |pick|
          %tr
            - if team_loss(pick[0])==true
              %td.mm.loss= pick[0]
              %td.mm.loss{:align => "right"}= pick[1]
            - else
              %td= pick[0]
              %td{:align => "right"}= pick[1]
    .col-md-5
      %h2
        Leaders
        = link_to 'View All', leaders_path, class: "btn btn-info"
      %table.table
        - @leaders.each do |leader|
          %tr
            %td
              = leader.name
            %td{:align => "right"}= leader.total_points
  %div

app/views/home/_not_logged_in.html.haml
= image_tag("bball_court.jpg", class: 'bg')

app/views/home/index.html.haml
- if user_signed_in?
  = render :partial => 'logged_in'
- else
  - render :partial => 'not_logged_in'