config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'sheets/my_brackets' => 'sheets#my_brackets', :as => :my_brackets
  get 'sheets/get_points' => 'sheets#get_points', :as => :points
  get 'sheets/leaders' => 'sheets#leaders', :as => :leaders
  get 'sheets/lock_sheets' => 'sheets#lock_sheets', :as => :lock_sheets

  resources :sheets, except: [ :index ] do
    member do
      get :mark_paid
    end
  end
  
  resources :teams do
    member do
      get :team_lost
    end
  end

  root to: "home#index"
end

app/views/layouts/_header.html.haml
- if user_signed_in?
  .div.mmnav
    %ul
      %li
        %a.navbar-brand{:href => "#"}
          Brackets #{Time.now.strftime("%Y")}
      %li
        = link_to 'Home', root_path
      %li
        - if policy(Sheet).my_brackets? 
          = link_to 'My Brackets', my_brackets_path
      %li
        = link_to 'Leaders', leaders_path
      %li
        = link_to "Edit Profile", edit_user_registration_path(current_user)
      - if policy(Team).index? 
        %li= link_to "Teams", teams_path
      %li
        = link_to "Logout", destroy_user_session_path, :method => :delete

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title Brackets
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    
  %body
    = render :partial => 'layouts/header'
    - flash.each do |key, value|
      %div{:class => flash_class(key)}
        %button.close{"data-dismiss" => "alert", :type => "button"} ×
        = value
    = yield